// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(SimulationDbContext))]
    partial class SimulationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Data.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRecordId");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Data.SimulationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultDeathProbability")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultSpreadingSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImmunityLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SicknessLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SimulationRecords");
                });

            modelBuilder.Entity("Data.LogEntry", b =>
                {
                    b.HasOne("Data.SimulationRecord", "SimulationRecord")
                        .WithMany("LogEntries")
                        .HasForeignKey("SimulationRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRecord");
                });

            modelBuilder.Entity("Data.SimulationRecord", b =>
                {
                    b.Navigation("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
