<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Mapsui.Avalonia" Version="5.1.0" />
    <PackageReference Include="Mapsui.Nts" Version="5.1.0" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="4.0.0" />
  </ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" Exclude="Assets\worldmap.geojson" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Assets\worldmap.geojson">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Services\Services.csproj" />
	  <ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\SimulationView.axaml.cs">
	    <DependentUpon>SimulationView.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>
</Project>
